Various improvements
- Allow usage of OAuth Key for authorization
- Add tailscale_proxy pass-through script
- Auto-configure Rails apps
- Reduce stdout noise when starting Tailscale and ProxyChains

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,21 +1,12 @@
 #!/usr/bin/env bash
-#
-# The 'compile' script is executed by the slug compiler with three arguments:
-#
-# - $1: build_dir, location of your app directory on the build dyno
-# - $2: cache_dir, directory on the build dyno that persists between builds
-# - $3: env_dir, directory holding all the app's config vars as files
-#
-# More information here: https://devcenter.heroku.com/articles/buildpack-api
-#------------------------------------------------------------------------------#
+# bin/compile <build-dir> <cache-dir> <env-dir>
 
-set -euo pipefail
-
-# debug
-# set -x
-
-# clean up leaking environment
-unset GIT_DIR
+# configure environment
+set -e            # fail fast
+set -o pipefail   # don't ignore exit codes when piping output
+shopt -s nullglob # allow file pattern to expand to null
+unset GIT_DIR     # clean up leaking environment
+# set -x          # enable debugging
 
 function log() {
     echo "-----> $*"
@@ -25,20 +16,17 @@ function indent() {
     sed -e 's/^/       /'
 }
 
-# parse and derive params
+# setup variables
 BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
 BUILDPACK_DIR="$(dirname "$(dirname "$0")")"
+BUILDPACK_VARIABLES="TAILSCALE_BUILD_TS_TARGETARCH"
 
-PC_BASE_DIR=$CACHE_DIR/proxychains-ng
-PC_SOURCE_DIR=$CACHE_DIR/proxychains-ng/source
-mkdir -p $PC_SOURCE_DIR
-
-BUILDPACK_VARIABLES="TAILSCALE_BUILD_TS_VERSION TAILSCALE_BUILD_TS_TARGETARCH"
-
-shopt -s nullglob
-DEFAULT_TAILSCALE_BUILD_TS_VERSION=1.74.0
+TAILSCALE_VERSION=1.74.0
+PROXYCHAINS_VERSION=4.17
+TAILSCALE_INSTALL_DIR="$BUILD_DIR/vendor/tailscale"
+PC_INSTALL_DIR="$BUILD_DIR/vendor/proxychains-ng"
 
 # Load any tailscale build environment variables for the application
 # into the actual environment variables.
@@ -53,13 +41,6 @@ else
   log "Using Tailscale architecture from TAILSCALE_BUILD_TS_TARGETARCH config var: $TAILSCALE_BUILD_TS_TARGETARCH"
 fi
 
-if [ -z "${TAILSCALE_BUILD_TS_VERSION:-}" ] ; then
-  export TAILSCALE_BUILD_TS_VERSION=$DEFAULT_TAILSCALE_BUILD_TS_VERSION
-  log "No Tailscale version specified in TAILSCALE_BUILD_TS_VERSION config var. Defaulting to $TAILSCALE_BUILD_TS_VERSION."
-else
-  log "Using Tailscale version from TAILSCALE_BUILD_TS_VERSION config var: $TAILSCALE_BUILD_TS_VERSION"
-fi
-
 if [ -z "${TAILSCALE_BUILD_PROXYCHAINS_REPO:-}" ] ; then
   export TAILSCALE_BUILD_PROXYCHAINS_REPO="https://github.com/rofl0r/proxychains-ng.git"
   log "No ProxyChains repo specified in TAILSCALE_BUILD_PROXYCHAINS_REPO config var. Defaulting to $TAILSCALE_BUILD_PROXYCHAINS_REPO."
@@ -67,58 +48,56 @@ else
   log "Using ProxyChains repo from TAILSCALE_BUILD_PROXYCHAINS_REPO config var: $TAILSCALE_BUILD_PROXYCHAINS_REPO"
 fi
 
-
 log "Install Tailscale"
-log "Add Tailscale to the PATH"
-mkdir -p "$BUILD_DIR/vendor/tailscale"
-export PATH="$BUILD_DIR/vendor/tailscale:$PATH"
-
-log "Fetch Tailscale"
-curl -sL "https://pkgs.tailscale.com/stable/tailscale_${TAILSCALE_BUILD_TS_VERSION}_${TAILSCALE_BUILD_TS_TARGETARCH}.tgz" \
-  | tar -zxf - -C "${BUILD_DIR}/vendor/tailscale" --strip=1 tailscale_${TAILSCALE_BUILD_TS_VERSION}_${TAILSCALE_BUILD_TS_TARGETARCH}/tailscaled tailscale_${TAILSCALE_BUILD_TS_VERSION}_${TAILSCALE_BUILD_TS_TARGETARCH}/tailscale
-# Mark the scripts as executable.
-chmod +x "$BUILD_DIR/vendor/tailscale/tailscale"
-chmod +x "$BUILD_DIR/vendor/tailscale/tailscaled"
-cp "$BUILDPACK_DIR/bin/heroku-tailscale-start.sh" "$BUILD_DIR/vendor/tailscale/heroku-tailscale-start.sh"
-cp "$BUILDPACK_DIR/bin/heroku-tailscale-test.sh" "$BUILD_DIR/vendor/tailscale/heroku-tailscale-test.sh"
-chmod +x "$BUILD_DIR/vendor/tailscale/heroku-tailscale-start.sh"
-chmod +x "$BUILD_DIR/vendor/tailscale/heroku-tailscale-test.sh"
-
-mkdir -p $BUILD_DIR/.profile.d 2>&1 | indent
-rm -f $BUILD_DIR/.profile.d/heroku-tailscale-buildpack.sh 2>&1 | indent
-echo 'export PATH="/app/vendor/tailscale:$PATH"' >> $BUILD_DIR/.profile.d/heroku-tailscale-buildpack.sh 2>&1 | indent
+mkdir -p $TAILSCALE_INSTALL_DIR
+export PATH="$TAILSCALE_INSTALL_DIR:$PATH"
+curl -sL "https://pkgs.tailscale.com/stable/tailscale_${TAILSCALE_VERSION}_${TAILSCALE_BUILD_TS_TARGETARCH}.tgz" \
+  | tar -zxf - -C "$TAILSCALE_INSTALL_DIR" --strip=1 tailscale_${TAILSCALE_VERSION}_${TAILSCALE_BUILD_TS_TARGETARCH}/tailscaled tailscale_${TAILSCALE_VERSION}_${TAILSCALE_BUILD_TS_TARGETARCH}/tailscale
+chmod +x "$TAILSCALE_INSTALL_DIR/tailscale"
+chmod +x "$TAILSCALE_INSTALL_DIR/tailscaled"
+cp "$BUILDPACK_DIR/bin/heroku-tailscale-start.sh" "$TAILSCALE_INSTALL_DIR/heroku-tailscale-start.sh"
+cp "$BUILDPACK_DIR/bin/heroku-tailscale-test.sh" "$TAILSCALE_INSTALL_DIR/heroku-tailscale-test.sh"
+chmod +x "$TAILSCALE_INSTALL_DIR/heroku-tailscale-start.sh"
+chmod +x "$TAILSCALE_INSTALL_DIR/heroku-tailscale-test.sh"
+mkdir -p $BUILD_DIR/.profile.d
+echo 'export PATH="/app/vendor/tailscale:$PATH"' >> $BUILD_DIR/.profile.d/heroku-tailscale-buildpack.sh
 
 log "Install ProxyChains-ng"
-
-log "Clone ProxyChains repo"
-rm -r $PC_SOURCE_DIR
-git clone $TAILSCALE_BUILD_PROXYCHAINS_REPO $PC_SOURCE_DIR 2>&1 | indent
-
-pushd $PC_SOURCE_DIR > /dev/null
-PC_VERSION_TAG=$(git describe --tags| cut -d- -f1)
-CACHED_BUILD_DIR=$PC_BASE_DIR/proxychains-ng-$PC_VERSION_TAG
-
-if [[ ! -d $CACHED_BUILD_DIR ]]; then
-  log "Building ProxyChains $PC_VERSION_TAG"
-  make clean 2>&1 | indent
-  git checkout $PC_VERSION_TAG 2>&1 | indent
-  ./configure --prefix=/app/vendor/proxychains-ng 2>&1 | indent
-  make 2>&1 | indent
-  DESTDIR=$CACHED_BUILD_DIR make install 2>&1 | indent
+PC_BUILD_DIR="$CACHE_DIR/proxychains-ng-$PROXYCHAINS_VERSION"
+if [ ! -f "$PC_BUILD_DIR/proxychains4" ]; then  
+  rm -rf $PC_BUILD_DIR  
+  wget "https://github.com/rofl0r/proxychains-ng/archive/refs/tags/v$PROXYCHAINS_VERSION.tar.gz" -O $CACHE_DIR/proxychains.tar.gz
+  cd $CACHE_DIR
+  tar -zxvf $CACHE_DIR/proxychains.tar.gz
+  cd $PC_BUILD_DIR
+  make clean
+  ./configure --libdir=/app/vendor/proxychains-ng
+  make
 fi
-popd > /dev/null
-
-log "Installing ProxyChains into the slug"
-mkdir -p "$BUILD_DIR/vendor/proxychains-ng"
-cp -r "$BUILDPACK_DIR/conf" "$BUILD_DIR/vendor/proxychains-ng/conf"
-echo 'export PATH="/app/vendor/proxychains-ng/bin:$PATH"' >> $BUILD_DIR/.profile.d/heroku-tailscale-buildpack.sh 2>&1 | indent
-echo 'export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/app/vendor/proxychains-ng/lib";' >> $BUILD_DIR/.profile.d/heroku-tailscale-buildpack.sh 2>&1 | indent
+mkdir $PC_INSTALL_DIR
+cp $PC_BUILD_DIR/libproxychains4.so $PC_BUILD_DIR/proxychains4 $BUILDPACK_DIR/conf/proxychains.conf $PC_INSTALL_DIR
+echo 'export PATH="/app/vendor/proxychains-ng:$PATH"' >> $BUILD_DIR/.profile.d/heroku-tailscale-buildpack.sh
 
 if [[ "${TAILSCALE_BUILD_EXCLUDE_START_SCRIPT_FROM_PROFILE_D:-}" != "True" ]]; then
+  log "Configuring Tailscale to start when booting"
   # Add the line to start tailscale to the end of the file
-  echo "/app/vendor/tailscale/heroku-tailscale-start.sh" >> $BUILD_DIR/.profile.d/heroku-tailscale-buildpack.sh 2>&1 | indent
+  echo "/app/vendor/tailscale/heroku-tailscale-start.sh" >> $BUILD_DIR/.profile.d/heroku-tailscale-buildpack.sh
 fi
 
-pushd $CACHED_BUILD_DIR/app > /dev/null
-cp -rv ./ $BUILD_DIR 2>&1 | indent
-popd > /dev/null
+log "Moving the tailscale_proxy into app/bin"
+mkdir -p $BUILD_DIR/bin
+cp "$BUILDPACK_DIR/bin/tailscale_proxy" $BUILD_DIR/bin/
+chmod +x $BUILD_DIR/bin/tailscale_proxy
+
+if [ -f "$BUILD_DIR/bin/rails" ]; then
+  log "Rails app detected: Will replace bin/rails, bin/bundle, and bin/rake with passthrough scripts to tailscale_proxy"
+  mv $BUILD_DIR/bin/rails $BUILD_DIR/bin/rails_original
+  cp "$BUILDPACK_DIR/bin/rails/rails" $BUILD_DIR/bin/
+  chmod +x $BUILD_DIR/bin/rails
+  mv $BUILD_DIR/bin/bundle $BUILD_DIR/bin/bundle_original
+  cp "$BUILDPACK_DIR/bin/rails/bundle" $BUILD_DIR/bin/
+  chmod +x $BUILD_DIR/bin/bundle
+  mv $BUILD_DIR/bin/rake $BUILD_DIR/bin/rake_original
+  cp "$BUILDPACK_DIR/bin/rails/rake" $BUILD_DIR/bin/
+  chmod +x $BUILD_DIR/bin/rake
+fi
